# To run: conda env create -f environment.yaml
name: Haptic-PBR-Maps
channels:
    - defaults
    - pytorch
dependencies:
    - python
    - pip
    - cudatoolkit
    - numpy
    - pytorch
    - torchvision
    - configargparse
    - pip:
        - opencv-python-headless>=4.4.0.42
        - scipy>=1.9.0
        - matplotlib
        - datasets
        - diffusers
        - setuptools
        - transformers
        - accelerate
        - moderngl
